---

- name: config | .zshrc
  become: true
  ansible.builtin.template:
    src: zshrc.j2
    dest: '{{ ohmyzsh_user_home }}/.zshrc'
    owner: '{{ ohmyzsh_user_name }}'
    group: '{{ ohmyzsh_user_group }}'
    mode: '0644'
    backup: true
    force: true
    validate: zsh -n %s

- name: config | .zshrc.d
  become: true
  ansible.builtin.file:
    path: '{{ ohmyzsh_user_home }}/.zshrc.d'
    state: directory
    owner: '{{ ohmyzsh_user_name }}'
    group: '{{ ohmyzsh_user_group }}'
    mode: '0755'

- name: config | starship config directory
  become: true
  ansible.builtin.file:
    path: '{{ ohmyzsh_starship_config_path | dirname }}'
    state: directory
    owner: '{{ ohmyzsh_user_name }}'
    group: '{{ ohmyzsh_user_group }}'
    mode: '0755'

- name: config | starship.toml
  become: true
  ansible.builtin.template:
    src: starship.toml.j2
    dest: '{{ ohmyzsh_starship_config_path }}'
    owner: '{{ ohmyzsh_user_name }}'
    group: '{{ ohmyzsh_user_group }}'
    mode: '0644'
    backup: true

- name: config | remove powerlevel10k config
  become: true
  ansible.builtin.file:
    path: '{{ ohmyzsh_user_home }}/.p10k.zsh'
    state: absent
