---

galaxy_info:
  role_name: dock
  namespace: flyoverhead
  author: flyoverhead
  description: macOS Dock contents and ordering via dockutil
  license: GPL-3.0-only
  min_ansible_version: '2.16'
  platforms:
    - name: MacOSX
      versions:
        - all
  galaxy_tags:
    - dock
    - dockutil
    - macos

dependencies: []
